# fly.toml app configuration file generated for fridge-wall on 2024-02-14T22:08:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fridge-wall'
primary_region = 'ord'

[build]

[mounts]
source = 'data'
destination = '/data'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
